import static org.junit.Assert.*;

import dup1n.bioinformatics.Cutter;
import dup1n.bioinformatics.Genome;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class GenomeTest {

    // https://www.ncbi.nlm.nih.gov/nuccore/MW015936.1?report=genbank
    Genome zika = new Genome("""
                AGTTGTTGATCTGTGTGAATCAGACTGCGACAGTTCGAGTTTGAAGCGAAAGCTAGCAACAGTATCAACA
                GGTTTTATTTTGGATTTGGAAACGAGAGTTTCTGGTCATGAAAAACCCAAAGAAGAAATCCGGAGGATTC
                CGGATTGTCAATATGCTAAAACGCGGAGTAGCCCGTGTGAGCCCCTTTGGGGGCTTGAAGAGGCTGCCAG
                CCGGACTTCTGCTGGGTCATGGGCCCATCAGGATGGTCTTGGCGATTCTAGCCTTTTTGAGATTCACGGC
                AATCAAGCCATCACTGGGTCTCATCAATAGATGGGGTTCAGTGGGGAAAAAAGAGGCTATGGAAATAATA
                AAGAAGTTCAAGAAAGATCTGGCTGCCATGCTGAGAATAATCAATGCTAGGAAGGAGAAGAAGAGACGAG
                GCACAGATACTAGTGTCGGAATTGTTGGCCTCCTGCTGACCACAGCCATGGCAGTGGAGGTCACTAGACG
                TGGGAGTGCATACTATATGTACTTGGACAGAAGTGATGCTGGGGAGGCCATATCTTTTCCAACCACACTG
                GGGATGAATAAGTGTTATATACAGATCATGGATCTTGGACACATGTGTGATGCCACCATGAGCTATGAAT
                GCCCTATGCTGGATGAGGGGGTAGAACCAGATGACGTCGATTGTTGGTGCAACACGACGTCAACTTGGGT
                TGTGTACGGAACCTGCCACCACAAAAAAGGTGAAGCACGGAGATCTAGAAGAGCTGTGACGCTCCCCTCC
                CATTCCACTAGGAAGCTGCAAACGCGGTCGCAGACCTGGTTGGAATCAAGAGAATACACAAAGCACTTGA
                TTAGAGTCGAAAATTGGATATTCAGGAACCCTGGCTTCGCGTTAGCAGCAGCTGCCATCGCTTGGCTTTT
                GGGAAGCTCAACGAGCCAAAAAGTCATATACTTGGTCATGATACTGCTGATTGCCCCGGCATACAGCATC
                AGGTGCATAGGAGTCAGCAATAGGGACTTTGTGGAAGGTATGTCAGGTGGGACTTGGGTTGATGTTGTCT
                TGGAACATGGAGGTTGTGTTACCGTAATGGCACAGGACAAACCGACTGTCGACATAGAGCTGGTTACAAC
                AACAGTCAGCAACATGGCGGAGGTAAGATCCTACTGCTATGAGGCATCAATATCGGACATGGCTTCGGAC
                AGCCGCTGCCCAACACAAGGTGAAGCCTACCTTGACAAGCAATCAGACACTCAATATGTCTGCAAAAGAA
                CGTTAGTGGACAGAGGCTGGGGAAATGGATGTGGACTTTTTGGCAAAGGGAGCCTGGTGACATGCGCTAA
                GTTTGCATGCTCTAAGAAAATGACCGGGAAGAGCATCCAGCCAGAGAATCTGGAGTACCGGATAATGCTG
                TCAGTTCATGGCTCCCAGCACAGTGGGATGATCGTTAATGACACAGGACATGAAACTGATGAGAATAGAG
                CGAAGGTTGAGATAACGCCCAATTCACCAAGAGCCGAAGCCACCCTGGGGGGTTTTGGAAGCCTAGGACT
                TGATTGTGAACCGAGGACAGGCCTTGACTTTTCAGACTTGTATTACTTGACTATGAATAACAAGCACTGG
                TTGGTTCACAAGGAGTGGTTCCACGACATTCCATTACCTTGGCATGCTGGGGCAGACACCGGAACTCCAC
                ACTGGAACAACAAAGAAGCACTGGTAGAGTTCAAGGACGCACATGCCAAAAGGCAAACTGCCGTGGTTCT
                AGGGAGTCAAGAAGGAGCAGTTCACACGGCCCTTGCTGGAGCTCTGGAGGCTGAGATGGATGGTGCAAAG
                GGAAGGCTGTCCTCTGGCCACTTGAAATGTCGCCTGAAAATGGATAAACTTAGATTGAAGGGCGTGTCAT
                ACTCCTTGTGTACCGCATCGTTCACATTCACTAAGATCCCGGCTGAAACACTGCACGGGACAGTCACAGT
                GGAGGTACAGTACGCAGGGACAGATGGACCTTGCAAGGTTCCAGCTCAGATGGCGGTGGACATGCAAACT
                CTGACCCCAGTTGGGAGGTTGATAACCGCTAACCCTGTAATCACTGAAAGCACTGAGAACTCTAAGATGA
                TGCTGGAACTTGATCCACCATTTGGGGACTCTTACATTGTCATAGGAGTCGGGGAGAAGAAGATCACCCA
                CCACTGGCACAGGAGTGGCAGCACCATTGGAAAAGCATTTGAAGCCACTGTGAGAGGTGCCAAGAGAATG
                GCAGTCTTGGGAGACACAGCCTGGGACTTTGGATCAGTTGGAGGTGCTCTCAACTCACTGGGCAAGGGCA
                TCCATCAAATTTTTGGAGCAGCTTTCAAATCATTGTTTGGAGGAATGTCCTGGTTCTCACAAATTCTCAT
                TGGAACGTTGCTGGTGTGGTTGGGTCTGAATACAAAGAATGGATCTATTTCCCTTATGTGCTTGGCCTTA
                GGGGGAGTGTTGATCTTCTTATCCACAGCCGTCTCTGCTGATGTGGGGTGCTCGGTGGACTTCTCAAAGA
                AGGAAACGAGATGCGGTACAGGGGTGTTCGTCTATAACGACGTTGAAGCCTGGAGGGACAGGTACAAGTA
                CCATCCTGACTCCCCTCGTAGATTGGCAGCAGCAGTCAAGCAAGCCTGGGAAGATGGGATCTGTGGGATC
                TCCTCTGTTTCAAGAATGGAAAACATCATGTGGAGATCAGTAGAAGGGGAGCTCAACGCAATCCTGGAAG
                AGAATGGAGTTCAACTGACGGTCGTTGTGGGATCTGTAAAAAACCCCATGTGGAGAGGTCCACAGAGATT
                GCCCGTGCCTGTGAACGAGCTGCCCCACGGCTGGAAGGCTTGGGGGAAATCGTACTTCGTCAGAGCAGCA
                AAGACAAATAACAGCTTTGTCGTGGATGGTGACACACTGAAGGAATGCCCACTCAAACATAGAGCATGGA
                ACAGCTTTCTTGTGGAGGATCATGGGTTCGGGGTATTTCACACTAGTGTCTGGCTCAAGGTTAGAGAAGA
                TTATTCATTAGAGTGTGATCCAGCCGTCATTGGAACAGCCGCTAAGGGAAAGGAGGCTGTGCACAGTGAT
                CTAGGCTACTGGATTGAGAGTGAGAAGAACGACACATGGAGGCTGAAGAGGGCCCACCTGATCGAGATAA
                AAACATGTGAATGGCCGAAGTCCCACACATTGTGGACAGATGGAATAGAAGAAAGTGATCTGATCATACC
                CAAGTCTTTAGCTGGGCCACTCAGCCATCACAACACCAGAGAGGGCTACAGGACCCAAATGAAAGGGCCA
                TGGCACAGTGAAGAGCTTGAAATTCGGTTTGAGGAATGCCCAGGCACTAAGGTCCACGTGGAGGAAACAT
                GTGGAACAAGAGGACCATCTCTGAGATCAACCACTGCAAGCGGAAGGGTGATCGAGGAATGGTGCTGCAG
                GGAGTGCACAATGCCCCCACTGTCGTTCCGGGCTAAAGATGGTTGTTGGTATGGAATGGAGATAAGGCCC
                AGGAAAGAACCAGAAAGTAACTTAGTAAGGTCAATGGTGACTGCAGGATCAACTGATCACATGGATCACT
                TCTCCCTTGGAGTGCTTGTGATTCTGCTCATGGTGCAGGAAGGGCTGAAGAAGAGAATGACCACAAAGAT
                CATCATAAGCACATCAATGGCAGTGCTGGTAGCTATGATCCTGGGAGGATTTTCAATGAGTGACCTGGCT
                AAGCTTGCAATTTTGATGGGTGCCACCTTCGCGGAAATGAACACTGGAGGAGATGTAGCTCATCTGGCGC
                TGATAGCGGCATTCAAAGTCAGACCTGCGTTGCTGGTATCTTTCATCTTCAGAGCTAATTGGACACCCCG
                TGAGAGCATGCTGCTGGCCTTGGCCTCGTGTCTTCTGCAAACTGCGATCTCCGCCTTGGAAGGCGACCTG
                ATGGTTCTCATCAATGGTTTTGCTTTGGCCTGGTTGGCAATACGAGCGATGGTTGTTCCACGCACTGACA
                ACATCACCTTGGCAATCCTGGCTGCTCTGACACCACTGGCCCGGGGCACACTGCTTGTGGCGTGGAGAGC
                AGGCCTTGCTACTTGCGGGGGGTTCATGCTCCTCTCTCTGAAGGGGAGAGGCAGTGTGAAGAAGAACTTA
                CCATTTGTCATGGCCCTGGGACTAACCGCTGTGAGGCTGGTCGACCCCATCAACGTGGTGGGACTGCTGT
                TGCTCACAAGGAGTGGGAAGCGGAGCTGGCCCCCTAGTGAAGTACTCACAGCTGTTGGCCTGATATGCGC
                ATTGGCTGGAGGGTTCGCCAAGGCGGATATAGAGATGGCTGGGCCCATAGCCGCGGTCGGTCTGCTAATT
                GTCAGTTACGTGGTCTCAGGAAAGAGTGTGGACATGTACATTGAAAGAGCAGGTGACATCACATGGGAAA
                AAGATGCGGAAGTCACTGGAAACAGTCCCCGGCTCGATGTGGCACTAGATGAGAGTGGTGATTTCTCCCT
                AGTGGAGGATGATGGTCCCCCCATGAGAGAGATCATACTCAAAGTGGTCCTGATGGCCATCTGTGGCATG
                AACCCAATAGCCATACCCTTTGCAGCTGGAGCGTGGTACGTGTATGTGAAGACTGGAAAAAGGAGTGGTG
                CTCTATGGGATGTGCCTGCTCCCAAGGAAGTAAAAAAGGGGGAGACCACAGATGGAGTGTACAGAGTAAT
                GACTCGCAGACTGCTAGGTTCAACACAAGTTGGAGTGGGAGTCATGCAAGAGGGGGTCTTCCACACTATG
                TGGCACGTCACAAAAGGATCCGCGCTGAGAAGCGGTGAAGGGAGACTTGATCCATACTGGGGAGATGTCA
                AGCAGGATCTGGTGTCATACTGTGGTCCATGGAAGCTAGATGCCGCCTGGGACGGGCACAGCGAGGTGCA
                GCTCTTGGCCGTGCCCCCCGGAGAGAGAGCGAGGAACATCCAGACTCTGCCCGGAATATTTAAGACAAAG
                GATGGGGACATTGGAGCAGTTGCGCTGGACTACCCAGCAGGAACTTCAGGATCTCCAATCCTAGATAAGT
                GTGGGAGAGTGATAGGACTCTATGGTAATGGGGTCGTGATCAAAAATGGGAGTTATGTTAGTGCCATCAC
                CCAAGGGAGGAGGGAGGAAGAGACTCCTGTTGAGTGCTTCGAGCCTTCGATGCTGAAGAAGAAGCAGCTA
                ACTGTCTTAGACTTGCATCCTGGAGCTGGGAAAACCAGGAGAGTTCTTCCCGAAATAGTCCGTGAAGCCA
                TAAAAACAAGACTCCGTACTGTGATCTTAGCTCCAACCAGGGTTGTCGCTGCTGAAATGGAGGAAGCCCT
                TAGAGGGCTTCCAGTGCGTTATATGACAACAGCAGTCAATGTCACCCATTCTGGGACAGAAATCGTTGAC
                TTAATGTGCCATGCCACCTTCACTTCACGTCTACTACAGCCAATCAGAGTCCCCAACTATAATCTGTATA
                TTATGGATGAGGCCCACTTCACAGATCCCTCAAGTATAGCAGCAAGAGGATACATTTCAACAAGGGTTGA
                GATGGGCGAGGCGGCTGCCATCTTCATGACTGCCACGCCACCAGGAACCCGTGACGCATTCCCGGACTCC
                AACTCACCAATTATGGACACCGAAGTGGAAGTCCCAGAGAGAGCCTGGAGCTCAGGCTTTGATTGGGTGA
                CGGATCATTCTGGAAAAACAGTTTGGTTTGTTCCAAGCGTGAGGAACGGCAATGAGATCGCAGCTTGTCT
                GACAAAGGCTGGAAAACGGGTCATACAGCTCAGCAGAAAGACTTTTGAGACAGAGTTCCAGAAAACAAAA
                CATCAAGAGTGGGACTTCGTCGTGACAACTGACATTTCAGAGATGGGCGCCAACTTTAAAGCTGACCGTG
                TCATAGATTCCAGGAGATGCCTAAAGCCGGTCATACTTGATGGCGAGAGAGTCATTCTGGCTGGACCCAT
                GCCTGTCACACATGCCAGCGCTGCCCAGAGGAGGGGGCGCATAGGCAGGAATCCCAACAAACCTGGAGAT
                GAGTATCTGTATGGAGGTGGGTGCGCAGAGACTGATGAAGACCATGCACACTGGCTTGAAGCAAGAATGC
                TTCTTGACAACATTTACCTCCAAGATGGCCTCATAGCCTCGCTCTATCGACCTGAGGCCGACAAAGTAGC
                AGCTATTGAGGGAGAGTTCAAGCTTAGGACGGAGCAAAGGAAGACCTTTGTGGAACTCATGAAAAGAGGA
                GATCTTCCTGTTTGGCTGGCCTATCAGGTTGCATCTGCCGGAATAACCTACACAGATAGAAGATGGTGCT
                TTGATGGCACGACCAACAACACCATAATGGAAGACAGTGTGCCGGCAGAGGTGTGGACCAGATACGGAGA
                GAAAAGAGTGCTCAAACCGAGGTGGATGGACGCCAGAGTTTGTTCAGATCATGCGGCCCTGAAGTCATTC
                AAAGAGTTTGCCGCTGGGAAAAGAGGAGCGGCCTTTGGAGTGATGGAAGCCCTGGGAACACTGCCAGGAC
                ACATGACAGAGAGATTCCAGGAGGCCATTGACAACCTCGCTGTGCTCATGCGGGCAGAGACTGGAAGCAG
                GCCCTACAAAGCCGCGGCGGCCCAATTGCCGGAGACCCTAGAGACCATCATGCTTTTGGGGTTGCTGGGA
                ACAGTCTCGCTGGGAATCTTTTTCGTCTTGATGCGGAACAAGGGCATAGGGAAGATGGGCTTTGGAATGG
                TGACTCTTGGGGCCAGCGCATGGCTTATGTGGCTCTCGGAAATTGAGCCAGCCAGAATTGCATGTGTCCT
                CATTGTTGTGTTCCTATTGCTGGTGGTGCTCATACCTGAGCCAGAAAAGCAAAGATCTCCCCAGGACAAC
                CAAATGGCAATCATCATCATGGTAGCAGTGGGTCTTCTGGGCTTGATTACCGCCAATGAACTCGGATGGT
                TGGAGAGAACAAAGAGTGACCTAAGCCATCTAATGGGAAGGAGAGAGGAGGGGGCAACCATAGGATTCTC
                AATGGACATTGACCTGCGGCCAGCCTCAGCTTGGGCTATCTATGCTGCTCTGACAACTTTCATTACCCCA
                GCCGTCCAACATGCAGTGACCACTTCATACAACAACTACTCCTTAATGGCGATGGCCACGCAAGCTGGAG
                TGTTGTTTGGTATGGGTAAAGGGATGCCATTCTACGCATGGGACTTTGGAGTCCCGCTGCTAATGATAGG
                TTGCTACTCACAATTAACACCCCTGACCCTAATAGTGGCCATCATTTTGCTCGTGGCGCACTACATGTAC
                TTGATCCCAGGGCTGCAGGCAGCAGCTGCGCGTGCTGCTCAGAAGAGAACGGCAGCTGGCATCATGAAGA
                ACCCTGTTGTGGATGGAATAGTGGTGACTGACATTGACACAATGACAATTGACCCCCAAGTGGAGAAAAA
                GATGGGACAGGTGCTACTCATAGCAGTAGCCGTCTCCAGCGCCATACTGTCGCGGACCGCCTGGGGGTGG
                GGGGAGGCTGGGGCCCTGATCACAGCTGCAACTTCCACTTTGTGGGAAGGCTCTCCGAACAAGTACTGGA
                ACTCCTCCACAGCCACTTCACTGTGTAACATTTTTAGGGGAAGTTACTTGGCTGGAGCTTCTCTAATCTA
                CACAGTAACAAGAAACGCTGGCTTGGTCAAGAGACGTGGGGGTGGAACGGGAGAGACCCTGGGAGAGAAG
                TGGAAGGCCCGCCTGAACCAGATGTCGGCCCTGGAGTTCTACTCCTACAAAAAGTCAGGCATCACCGAGG
                TGTGCAGAGAAGAGGCCCGCCGCGCCCTCAAGGACGGTGTGGCAACGGGAGGCCATGCTGTGTCCCGAGG
                AAGTGCAAAGCTGAGATGGTTGGTGGAGAGGGGATACCTGCAGCCCTATGGAAAGGTCATTGATCTTGGA
                TGTGGCAGAGGGGGCTGGAGTTACTACGCCGCCACCATCCGCAAAGTTCAAGAAGTGAAAGGATACACAA
                AAGGAGGCCCTGGTCATGAGGAACCCATGTTGGTGCAAAGCTATGGGTGGAACATAGTCCGTCTTAAGAG
                TGGGGTGGACGTCTTTCATATGGCGGCTGAGCCGTGTGACACGTTGCTGTGTGATATAGGTGAGTCATCA
                TCTAGTCCTGAAGTGGAAGAAGCACGGACGCTCAGAGTCCTCTCCATGGTGGGGGATTGGCTTGAAAAAA
                GACCAGGAGCCTTTTGTATAAAAGTGTTGTGCCCATACACCAGCACTATGATGGAAACCCTGGAGCGACT
                GCAGCGTAGGTATGGGGGAGGACTGGTCAGAGTGCCACTCTCCCGCAACTCTACACATGAGATGTACTGG
                GTCTCTGGAGCGAAAAGCAACACCATAAAAAGTGTGTCCACCACGAGCCAGCTCCTCTTGGGGCGCATGG
                ACGGGCCCAGGAGGCCAGTGAAATATGAGGAGGATGTGAATCTCGGCTCTGGCACGCGGGCTGTGGTAAG
                CTGCGCTGAAGCTCCCAACATGAAGATCATTGGTAACCGCATTGAGAGGATCCGCAGTGAGCACGCGGAA
                ACGTGGTTCTTTGACGAGAACCACCCATATAGGACATGGGCTTACCATGGAAGCTACGAGGCCCCCACAC
                AAGGGTCAGCGTCCTCTCTAATAAACGGGGTTGTCAGGCTCCTGTCAAAACCCTGGGATGTGGTGACTGG
                AGTCACAGGAATAGCCATGACCGACACCACACCGTATGGTCAGCAAAGAGTTTTCAAGGAAAAAGTGGAC
                ACTAGGGTGCCAGACCCCCAAGAAGGCACTCGTCAGGTTATGAGCATGGTCTCTTCCTGGTTGTGGAAAG
                AGCTAGGCAAACACAAACGGCCACGAGTCTGTACCAAAGAAGAGTTCATCAACAAGGTTCGTAGCAATGC
                AGCATTAGGGGCAATATTTGAAGAGGAAAAAGAGTGGAAGACTGCAGTGGAAGCTGTGAACGATCCAAGG
                TTCTGGGCTCTAGTGGACAAGGAAAGAGAGCACCACCTGAGAGGAGAGTGCCAGAGCTGTGTGTACAACA
                TGATGGGAAAAAGAGAAAAGAAACAAGGGGAATTTGGAAAGGCCAAGGGCAGCCGCGCCATCTGGTACAT
                GTGGCTAGGGGCTAGATTTCTAGAGTTCGAAGCCCTTGGATTCTTGAACGAGGATCACTGGATGGGGAGA
                GAGAATTCACGAGGTGGTGTTGAAGGGCTGGGATTACAAAGACTCGGATATGTCTTAGAAGAGATGAGTC
                GCATACCAGGAGGAAGGATGTATGCAGATGACACTGCTGGCTGGGACACCCGCATCAGCAGGTTTGATCT
                GGAGAATGAAGCTCTAATCACCAACCAAATGGAGAAAGGGCACAGGGCCTTGGCATTGGCCATAATCAAG
                TACACATACCAAAACAAAGTGGTAAAGGTCCTTAGACCAGCTGAAAAAGGGAAGACAGTTATGGACATTA
                TTTCAAGACAAGACCAAAGGGGGAGCGGACAAGTTGTCACTTACGCTCTTAATACATTTACCAACCTAGT
                GGTGCAGCTCATTCGGAATATGGAGGCTGAGGAAGTTCTAGAGATGCAAGACTTGTGGCTGCTGCGGAGG
                TCAGAGAAAGTGACCAACTGGTTGCAGAGCAATGGATGGGATAGGCTCAAACGAATGGCAGTCAGTGGAG
                ATGATTGCGTTGTGAAACCAATTGATGATAGGTTTGCACATGCTCTCAGGTTCTTGAATGATATGGGAAA
                AGTTAGGAAGGACACACAAGAGTGGAAACCCTCAACTGGATGGGACAACTGGGAAGAAGTTCCGTTTTGC
                TCCCACCACTTCAATAAGCTCCATCTCAAGGACGGGAGGTCCATTGTGGTTCCCTGCCGCCACCAAGATG
                AACTGATTGGCCGAGCCCGCGTCTCACCAGGGGCGGGATGGAGCATCCGGGAGACTGCTTGCCTAGCAAA
                ATCATATGCGCAAATGTGGCAGCTCCTTTATTTCCACAGAAGGGACCTCCGACTGATGGCCAATGCCATT
                TGTTCATCTGTGCCAGTTGACTGGGTTCCAACTGGGAGAACTACCTGGTCAATCCATGGAAAGGGAGAAT
                GGATGACCACTGAAGACATGCTTGTGGTGTGGAACAGAGTGTGGATTGAGGAGAACGACCACATGGAAGA
                CAAGACCCCAGTTACGAAATGGACAGACATTCCCTATTTGGGAAAAAGGGAAGACTTGTGGTGTGGGTCT
                CTCATAGGGCACAGACCGCGCACCACCTGGGCTGAGAACATTAAAAACACAGTCAACATGATGCGCAGGA
                TCATAGGTGATGAAGAAAAGTACATGGACTACCTATCCACCCAAGTTCGCTACTTGGGTGAAGAAGGGTC
                CACACCTGGAGTGCTATAAGCACCAGTCTTAGTGTTGTCAGGCCTGCTAGTCAGCCACAGCTTGGGGAAA
                GCTGTGCAGCCTGTGACCCCCCCAGGAGAAGCTGGGAAACCAAGCCCATAGTCAGGCCGAGAACGCCATG
                GCACGGAAGAAGCCATGCTGCCTGTGAGCCCCTCAGAGGACACTGAGTCAAAAAACCCCACGCGCTTGGA
                GGCGCAGGATGGGAAAAGAAGGTGGCGACCTTCCCCACCCTTCAATCTGGGGCCTGAACTGGAGATCAGC
                TGTGGATCTCCAGAAGAGGGACTAGTGGTTAGAGGAGACCCCCCGGAAAACGCAAAACAGCATATTGACG
                CTGGGAAAGACCAGAGACTCCATGAGTTTCCACCACGCTGGCCGCCAGGCACAGATCGCCGAATAGCGGC
                GGCCGGTGTGGGGAAATCCATGGGTCT
                """);

    // https://www.ncbi.nlm.nih.gov/nuccore/NC_067904.1
    Genome ixodesScapularis = new Genome("""
            TATAAAGTAAGCTAATTAAAGCTAGTGGGCTCATACCCCAAATATGAATAGATTTCCTTTATTAATATTT
            TATCAAAAAATTATTTTTTTATGAATTTTAGTATTATCAATTTTTATAGGGATTTCAAGTTCTTTTTGAT
            TTTCTTTATGAGTTTCATTAGAAATTAATATAATAATATTTATTCCATTAATAAATTCAAAAAATTTTTT
            ATCATCTAATAGAATTATAAATTATTATATTATTCAATCTTTTTCATCATCATTATTTCTTTTTTCATCA
            TTTTTAACTTTTTTTTTTTCTTCTTATATAATAGAATTAGTAATTTTAATTACCATAATAATTAAACTTG
            GAGCAGCTCCATTTCATGTATGATTCCCTCAAATTTCTGAAGGAATACATTTTTTTTCTTTTTTTATTCT
            TTTAACTTTTCAAAAAATTATTCCTCTTTTTATTTCATCTTTAATCTCTCATAATTTTTTTATTTTTTTT
            ATTATTTCTTCTAGTATAATTGGGTCTCTTGGGGGACTTAATCAAACTTCTTTTAAAAAAATTTTAGCTT
            TTTCTTCAATTTCTCATTTAGCATGAATAATAGCATTAATTTTTTCTAACCATAATTTTTGAATATTATA
            TTTGTTAATTTATTCTCTTATTACAATAAAAATCATTAAAATTTTTAAAAAAAATTATAACTTTTCAATT
            TTTAATTATAATTCAATAAAATTAACTTTTTTTAATAAAATTAGAATAGTTTCTTTTTTTTTATCCTTAG
            GAGGAATACCTCCTTTTCTTGGATTTTTCTCTAAATGAATTTCAGTTATTTTGATAATAAAAAATTTCCC
            ATTAATTATAATAATTTTAATCCCATCATCTTTAATTAATTTATTTTTTTATATTCGTATTTTATATCCA
            GTTATTTTAAATTTAAATATTTTAATAAAACCTCACCAATTTTTCGAAAACTTTTCAAAAAATTGAATAT
            TTTTCCCAAATTTTTTAAGTCTTATTATTTTAATCCCCTTGTTAATAATTATTTAAAGATTTTAAGTTAA
            AAAAACTATGTACCTTCAAAGTACAAATTAATTTAAATAATTAAATCTTAGATAGTTTATCTTCTTTAAA
            TTTGCAATTTAATATTTTTATAAAATATAAGATTAAAAAGTCTTAGTAAAAGAATTTTCTTCATTAATAA
            ATTTACAATTTATAGCTTAACAACTTCAGCCATTTTACCGCGATGATTATTTTCCACAAATCATAAAGAC
            ATTGGAACTATATATTTAATTTTTGGAAGCTGAGCAACTATAGTAGGAATATCTATAAGAATTTTAATTC
            GGACTGAATTAGGTCAACCAGGATCATTAATTGGTAATGACCAAATTTATAATGTTATTGTAACAGCTCA
            TGCATTTATTATAATTTTTTTTATAGTAATACCTGTAATAATTGGTGGTTTTGGTAATTGGTTAATTCCA
            TTAATATTAGGGGCACCAGACATAGCTTTCCCTCGTATAAACAATTTAAGCTTCTGGTTATTACCACCCT
            CTTTATTTTTATTAATTAATTCTTCTTTAGTAGAAAGGGGGGCAGGAACAGGCTGAACAGTATACCCACC
            ACTTTCATCTAACATTTCCCACTCTGGTGCTTCTGTTGATATAGCAATTTTTTCCCTCCATTTAGCAGGT
            ATTTCTTCAATTTTAGGAGCAATTAACTTTATTACAACAATTATTAATATACGATCTCCTGGAATATCTC
            TTGAACGCATACCATTATTTGTATGATCAGTTTTTATCACAGCAATTTTACTTCTTCTATCTCTTCCTGT
            TCTTGCTGGCGCAATTACAATGTTATTAACAGACCGTAATTTTAATACTTCGTTCTTTGACCCTTCTGGA
            GGAGGTGACCCTATTTTATATCAACATTTATTTTGATTTTTTGGCCATCCTGAAGTTTATATTCTTATTC
            TCCCTGGATTTGGCATGGTTTCTCATATTATTTGTTTTCATACAGGAAAAAAGGAACCTTTTGGAACATT
            AGGAATAATTTATGCAATATTAGCAATTGGTTTTTTAGGATTTATTGTTTGAGCACATCATATATTTACT
            GTAGGAATAGATATTGACACTCGAGCTTACTTTACTGCTGCAACTATAATTATTGCTGTCCCTACAGGAA
            TTAAAATTTTCAGATGACTTGCGACCCTTCATGGATCTAATATTAATTATAATTCTTCTATACTTTGAGT
            ATTAGGCTTTGTATTTTTATTTACTTTAGGTGGATTAACTGGTATTATTTTAGCTAATTCATCAATTGAT
            ATTATTTTACATGACACATACTATGTAGTAGCTCATTTTCACTATGTTCTCTCAATAGGAGCCGTTTTTG
            CTATTATAGGTTCAATTACACATTGATTTCCATTATTTTTTGGTTTAAATTTTAACTCTCTTTGGCTAAA
            AATTCAATTTTTTTCAATATTTATTGGAGTAAATATAACTTTTTTCCCACAACATTTCTTAGGATTAAGT
            GGGATACCACGACGATACTCAGATTATCCTGATTTTTTTTCTAAATGAAATTTAATTTCTTCATTAGGAA
            GAATAATTTCTTCTATAAGAGTAATTTTTTTTATCATTATTATATGAGATGCTATATCAACAAAAAAATT
            AATTCTTATTTCTCAATTTTCAAATTCTTCTAATGAATGACAATTAAATTTTCCACCTTCAGAGCATACT
            TTTAATCAAAATAATATTCTTATTAAATAATTAAACTAATGATAACTTGATCAAATATTATATTTTCTAA
            TAGAAACTCACCAATTATAGAACAAATAATTTTTTTCCACGATCATTCTATATTAATTATTTTTATAATT
            ACTATTATTACAATATATATAATTTTTAATATTATATCTAATTCATTTTCATCCCGATTCCTAATAGAAG
            GACAAGAAATTGAAACAATTTGAACAATTATCCCAGCAATTACATTAATTTTTATCGCTATACCATCTCT
            ACGTCTTCTCTATATACTAGATGAATCCTTTTCACCTTCAATTACTGTAAAAATTATTGGTCATCAATGG
            TATTGATCTTATGAATTTTCAGATTTTAATATTGAATTCGATTCTTTTATAATTCCTTCCCATGAAATAA
            AAGAAAATTCTTTCCGTTTACTTGATGTTGATAACCGAATAGTAATTCCTTTTAATTCTCATATTAAATT
            TTTAATTTCATCAGCTGATGTTATTCATTCATGGGCATTACCTTCATTAGGAATTAAAATAGATGCTGTT
            CCTGGACGTCTTAACCAATCTTTCTCATTTTCTTCTCGTCCTGGTTTATTTTTTGGACAATGTTCTGAAA
            TTTGTGGAGCAAATCATAGATTTATACCAATTTCTCTCGAAATTACATCCCCTAATAATTTTATTAAATG
            ATTAAAATCTTTTTCATTGAATGGCTGAAATATTTAAGCACTGGTCTCTTAAACCAATTTATAGTGAAAA
            TCACTTTCAATGGAAAAACTAGTTAAATTTATATAACATTAGAATGTCAATCTAAAATTACTTAAGTGTT
            TTTCAATTCCTCAACTATTTCCTATAAATTGAATTTTTTTATCTTTTTTTTTTTCTTTTTTTCTTAGATT
            TTCTTTAATTAATTTTTATTTTTTTGTTTTAAAAACAAAAAAATTAACACCAAATTTTTCTAATACTAAT
            AAATTTTTGTTAAAATGATAACAAACTTATTTTCAATTTTTGATCCCTCTTCATCATTAAATTTAAGAAT
            AAATTGAATTTCTGTTATTTCTATTTTATTTATTATACCAGCTAACTATTGAAGTATTTCTTCACGATAT
            CAAATACTTTGAAAAATTATTTTTATTAAAATTTTTGAAGAAATTAAAAATAATTTATCTATAAAATCTC
            AAAAATTTATTTTTATTTATCTTGCTCTTTTTTTTTCAATTTTAATATTTAATTGCTTAGGGTTAATTCC
            ATATGTTTTTACTCCATCTAGTCATATTATTTTATCAATAATCATAGCCTTCCCACTTTGAATAACTCTA
            ATATTAAAAGGTTGAATTACATCCTTCAATAAAATAATAACTCATTTAGTACCTCTTGGATCCCCTATAA
            TATTAACATTTTTTATAGTGATTATTGAAACTATTAGAAATTTAATTCGACCTATTACTTTATCCGTTCG
            TTTATCAGCCAACATAATTAGAGGCCACTTATTAATTCATCTTCTTACTTCAATTCCTTTTAATTACCCA
            AAAACTATTACAATTATTCTTCCTATTATATTATTTTTAATAATTTTGGAAACAGCAGTTGCTATAATTC
            AAAGCTATGTTTTCATTACTCTTTCATCTCTTTATACTAATGAAATTTAAAAACCAATGATATTTCATCC
            ATTCCATATAGTAGAAAAAAGACCATGACCTTTTTCTAGGTGTATTTCATCTATTATAATTACTATAAGA
            ACAATTTTAATACTTCATTTTTCATTTTCCTATATAATTTCTTTAGCATTAATTATTTTAATATTAACTC
            TTTTTCAATGGTGACGTGACGTCTCCCGAGAAGCAGCTCTCCAAGGTCTTCACTCTTCATATGTATTATG
            AGGATTAAAATTTGGTATAATTTTATTTATTATTTCTGAAATTTTCTTTTTTATTTCTTTTTTTTGGGCT
            TTTTTTCATAGAAGATTATCCCCTAATATTGAAATTGGAGCTATATGACCCCCGTTAAATATTTTTCCTT
            TTAATCCTTTTGAAATTCCTTTATTAAATACAACTATTTTAATTTCTTCTGGAATTTCAATTTCTTGATC
            ACATCATAGAATTATTAACAATAATTATAAAGAAGCCTTATATTCTTTACTAATCACCATTCTATTAGGT
            TTTACATTTTCAATCCTTCAAATATGAGAGTATATTCAAGCCCAATTCTCTATAAGTGATAGAATTTTCG
            GTTCATCATTTTTTATAACAACAGGTTTTCACGGAATTCATGTAATTATTGGAACAACTTTTTTAATTGT
            GTCTTTTTTCCGAATAAATAAAAATTTAATGTCATCAACTCATCATTTTGGCTTTGAAGCTGCTGCGTGG
            TACTGACATTTTGTTGATGTAGTATGATTATTTTTATTTACTTTTATGTATTGATGAATTTTTTGTTTAA
            TTAGTATAAATAAGTACATTTAATTTCCAATTAAAAAGTTTTTGAAAAAATTAAACAATAAAATTTACAA
            CTATTATAATAATCCCCTTTTTAATTCTTATTACTTTTTTTTTAATTTCTTTTAAAAATTTTTCTAATAA
            AGAAAAACTATCTCCTTTTGAGTGTGGATTTGACCCATTTTCTCTGTCACGAATTCCCTTTTCTTTAAAA
            TTTTTTTTGATTGCCATTATTTTTTTAATTTTTGATATTGAAATTGTAATTATTCTTCCTTTTCCTTTAT
            TATTTTTTAATAAAAATATATGATTTCTTATTTCATTTATTATTATTAATATTCTTATTAGATGGGGATT
            AATTTATGAGTGAAAAAAAGGAATACTTGAGTGACTTAAATAAAGAAAAGTATTTAAAAACTATAAAATC
            TAACTTGCAATTAGAAATTGATCTTTCCTTTTCTAAAAATAAAGCGATAAAAAATTGCAATCAGTTTCGA
            CCTGATCTTAGATGAATTCTATTTTTTTAATAGAAGCCAAAACCCCCGAGGCTATTCACTGTTAATGAAT
            AAATTGATATTTCCTATTAAAAACAAGATTAATAAATATAGACTTCTAATCTATTAATAATGATTATCAT
            TTAATCTTTATTTTTATAGTGTAAATAAACACTTAACATTTTCGTTGTTAAAATGATTTTTTATCTAAAA
            ATAAAATATTCTTAAAAATTATTTCTTTACATTTTCAGTGTAATATTTTTTTCTTCTATAAACTATAAGA
            ACATATAAACATATACATAATCAAAATGCTTGTATACAATAAAATTAGTGAACTTAAAAAATTATTTCTA
            AGCCAAATTGAAAAATAACTATTTTTTTGAAAAAATAAAAATACTCCTCCAGGACCTATTTCCTCCACCC
            ATTTCCAATCGTTTTCTGAAATAATTCTATATTTTTTAAAAAACTTTAATAAAACTGCTCTTGATAAAAT
            AGATATAAATCATATAGTTCTTAAAAAATAATAAATATATTTATAAAAATATCCTTTTATTTTTTCAATG
            AACATTAAATAAAACAAATAAAAAGAAAATAAAATTAAAATTAAATTAAAAAATTTACTAAAATTTGATA
            AAACAAGTAAATCCTCATAAATTATTATTAATCAACCAAATAAATTTCCAAAAACAATTACTATAAATCT
            TAAAAAATAAATAGGAAATAATATAAAATAATTAGAACCTTTTAAAAAAAAACTTTGAATAAAAATGCCT
            TTTCATACAATATAATATATTATTCGTATACAATAAATTATTGTTAATGATGTTCTTATAATTACAATTA
            TAATTATAAAAATGTTATTAATATTTATATAAATAAATTCTAAAATTAAATCTTTTGAATAAAACCCTCC
            TACAAAAGGAAATCCAAATAAAGATAAACTAGCTAAACCCATACAACCTCTAATTAAAGGTCTAAAATTA
            AAAAACCCCCCTAAATACCGGATATCTTGAATACCTGATAAGGTGTGAATCACTAATCCAGCACATAAAA
            ATAATATAGACTTAAATAATGCATGCATAAGTAAATGAAAAAAAGCTAACTCCATTTTTCCTAATGATAA
            AATTAATATAATTATTCCTAATTGTCTAAGAGTGGAAAAAGCAATAATTTTTTTGAAATCTAATTCTAAA
            TTTGCACCTACACCCGCTATAAATATAGTTATTCTTGAAAAAATTATTATAATTCTTGAATAAAATTTTA
            TTTCAAAAAGAATTCTAAAGCGAATTAAAAGATAAATTCCAGCAGTTACTAAAGTAGAAGAATGGACTAA
            AGAAGAAACGGGTGTAGGTGCAGCCATGGCTGCAGGTAATCATGCAGAAAAGGGAATTTGAGCTCTTTTT
            GTCATTCCTGAAACTATAATTATAATTCCACAAATTTTTAGTATTTCTTTTACTCTAATTATATCAAATC
            TCCCATAGTTAAATAAAAAAATTACTGATATAATAAGAGTTGCATCGCCTACTCGATTTATTAAAACAGT
            AATTATCCCAGAATTATAAGAATTAGAACTTTGATAGAAAATTACTAAACAATAAGAAACCAAACCTAAC
            CCATCTCAACCTAGAATAATTATTATTAAATTAGGCGAAACAATTAATAATAACATTGAAAATACAAATA
            ACAAAACTATATAACAAAAATAAATTTTTTCTCTTTCTCTTCTTATGTATTCATGTCTATAAATAATTAC
            TATAGCAGAAATTAATATAACTACAAACATAAATCTTAATCTAATTCAATCTAATAAAAAATATACTTTT
            ACATCAACAGATAATAAATTTATTAACAAAATTTCAATCACAATTACTTGATAAATATAAATTTTATAAA
            TAAATAAAATAAAAAAAATAAAACTATTAATTAACAAATAATATCCCCACTTTAAAAAAATTACTTAATG
            AAATTTCATCAATAAATCCACAATTTAATATTTTAATTTAAACTAATTAAGTTTTTAAATTCATCTTTCA
            AAACATTCTATTTTTAAAATTCAAATAATTAATGGGAAAAAATGAAAATATATTAATAAATGTTCACGGG
            CTGTAATTGAATTTACAGCTCATATAATTCAACCTTCCCCATGATTAATATAGCTAAATAAATATAAAGA
            GTAACCTGCTCTTAAAAACAAAAGAATTATTAAAGGAAATAAAAATATTATTCTTAATTTTAAAAGACTT
            CCCATTAAAAAAATTTCACCAAAAATATTTATGGAAGGTGGTGCTGCTATATTAAATACTCTTATTAAAA
            ATCATCATAAAGAAACAGAAGGGAAAATTTTATTTATTCCCTTTAGTAATAATAATCTTCGAGTAAAAAA
            ACGTTCATATAACATATTTCCTAAACAAAATAAACCAGATGAACATAACCCATGACCTAATATTAATAAT
            AAACTTCCAAAAGAACTTAAAAAATTTATTCTTATAATCCCCCTAAGAACAAGCCCTATATGACACACTG
            ATGAATAAGCAATCAAAGCTTTCAAATCTGTCTGAAATAAACATATTACACCTACAATTATTCTTCCTAA
            AATAGAAATAATTATTAAAACTCATCTTATTTCTATTAATTCTTTTAAAAAAAATATTTTAAAACGATAA
            ATACCATAAATTCCTAATTTTAATAAAACAGAAGCTAAAATTATTGAACCTGAAATAGGAGCCTCTACAT
            GAGCTTTCGGTAATCAAAGATGTAAAAAAAACATAGGAACTTTTACTAAAAAACCTAACATTATTAAAAA
            AAATAACAGTCCTATTGTTTTAAATTTTAAAAACTCTATATATAAATAATTTAATCTATAATCCTTAAAT
            ATAAATATAATGATAAATAAGGGAAGAGAACCCAATAATGTATATATTAATATATAAATACCTGCTTGTA
            AACGCTCAGGTTGATTGCCTCAATTAAAAATTATTATAATAATAGGGAATAAAATAGATTCAAAAAAAAA
            ATAAAATATTATTAAATTTGTCCTGTAAAAACATATATAAAGTAAAAATAATATAAAAAAAAGATAAAAT
            TTAAAATATTTATTTTCATAAAGCATTTCTTTAAATCTTGCTAACAATATTAAAATTATTATTCATACTG
            AAAGTATAAATAAATTTATTCTAAGAAGATCCCCCCCTAATTTATATATTATTATTCCTCCGTCGACATA
            ATTTAAAAAAACTAATCTTAAAAAAGAAAAAAGCACCAATATTAATTCTATTCCTTTTAAAAATATTGAT
            ATTCAAATTATCATAAATAACGAAATTAGTAATTTTAACATTTTAATATATATATAGAAGAAACTTGATC
            ATTTCCATAAAAAAAACTTATAATTACTATTAATCTTAAACCCAAACCCGCTTCAGCTACAATTAAAGTT
            AAATATACTAATGTTAATAAATAAGAATCAATTAGAACTATGCAATTAATTAATATAAATATTCTCAAAT
            ATATAAACTCAAATCTTAACAAAATTATTATTAAATAAAAACGATTTTTTAAAAAAGTTAATAATCCCAC
            CAAATACATAAAAATTGATAATTCTAACATTAGTTATAATAATTTAAAAAAAATAATGGTTTTGTAAACC
            AAATTTGATTATACTCTTATAATTTCAGAAAAGATTAATCTCTTTAAATATCCAAAATTTATGTACTCTT
            ATTATAATACTATTTTCTGAAATAAAATTTATAACTTTAATAACAACAATCTTTTTTATTTTTAATCACC
            CAATATATATATTAATATCAATCATTATAGTTACTTTAAGAATAAGAATTTTAATTTATAAAAGTATAAA
            AATAATGTGAATTCCTTTAATTTTAATTTTACTTATTTTGGGTGGAATATTTATTTTATTTCTTTATATT
            ATTAGATTAATTCCTAATAAAAAATTAACCTTTAATAAAAAAATTATAATATTAATAATTTTTTTATTAA
            TTTCTTTTCCTTTGTTTAAAATATCTGAAATTTCTTTTTTGTTCATAAATTCAAACTTTTTCCATTCTTC
            AATAAATATAATAATATTTATAATAATTTATCTAATTATTACTTTAATTGTAGTAATAAAACTTATAACT
            TCTTCTAACGCTCCCCTTTCAACTTCATAACTAATGAATTTAAAAAAAAAAATAAACCCAATTATTAATC
            TCCCCACCCCCTCTAATATTTCATATATATGAAATATAGGATCTCTTTTAGGAATATGTTTAAGAATTCA
            AATTCTTAGAGGTCTTTTTTTAGCAATAAATTTCTCAAGAGATATTAGTACAGCATTTAATATAATATCT
            CACATTTCACGAGATGTAAATAACGGCTGACTAATTCGATCAATTCACTCCAATGGGGCCTCAATATTTT
            TTATTTTTATGTATATCCACATTGGTCGAGGAATTTACCACTCTTCTTTTTTTTTTTTAAAAACTTGAAT
            AACAGGAATTATTATTATTTTTATTTTAATAGCTACAGCCTTCTTAGGATATGTTCTTCCTTGAGGGCAA
            ATATCCTTTTGGGGGGCAACAGTTATTACTAATTTATTCTCGGCCATTCCCTATATTGGCTCTATATTAA
            CATACTGAATTTGAGGGGGATTTTCAGTTGATAATAATACTCTTACTCGATTTTTTTCTCTTCACTTTAT
            CCTTCCTTTTGTATTATTACTTATGGTAATAATCCACATTATTATAATCCACGAAAAAGGATCAAGCAAC
            CCTCTAGGGCTAAACTTAAACATTGATAAAGTCCCTTTTCATCCTTATTTCACGGTAAAAGATATTTTAG
            GGTGTATAATTGCTTTATTTATTTTTTCCATTATTGTATTAATTATACCATATATTTTAAATGATTCAGA
            AAATTTCAATGTTGCAAATCCTTTAGTTACTCCTCCTCATATTCAACCTGAATGGTATTTTTTATTTGCA
            TATGCTATTCTTCGATCAATTCCTAATAAATTTGGAGGTGTAATTGCATTAGTAGCCTCAATTTTAATTA
            TTATTATTCTTCCCTTTTCTATAAAAAATAAATTTTCCTCTTTTTATTTTTTTCCATTAAAAAAGCTTTT
            TTTTTGAATTTTAGTAAATTTATTTTTATTATTAACATACTTTGGCGCATGCCCTGTAGAATACCCTTAT
            GTAATTATTAGACAATTTCTAACTTTATGCTATTTTTCTTTTTTCCTAATTATTCCTTTATTATGACTTT
            TTAACTATACATAAGTATATATTTTGAAAATATAAAAAAGAATTTTTTCTAAAAGTCTTTTTTTTTCTAA
            AAAGGACACAAATAATACTTATAATAATAATTTTATTAAAAAACATAAAAAAAATTATTATAATTCTAAA
            TGGTAAAATAACTTTTCATGCTAACATTATCAATTTATCATAACGATACCGAACTAAAGTTCCTCGAATT
            AAGATAAAAATTATCATTACAATTAATATATTAATTATTAAAATCCCCCCACAGCCAAAAAATAAATATG
            ATGTTACTAATCTAAATAAAATGATATTTCCATATTCTGCTATAAATAATAATGCAAAATTTCATGATCC
            GTACTCAACATTAAAACCCGATACTAATTCTGATTCTCCCTCAGATAAATCAAAAGGACTTCGATTAGTC
            TCAGCAAAACAAGAAACTATTCACACAAAAAATAAATTTAAAAACCCAACTCTTATTATTCAATAATCTT
            GAAATTTTCTTACATTTTCAATATTATAACTACCAGAAAAAAAAACAATGCTAATTAAAAGTAAAGAAAA
            ACTTACTTCATAAGAAATTACCTGAGCTACACCTCGATAAGCTCCTAATAAAGAATACTTAGAATTAGAA
            GACCATCCTCCTATTAAAATAATATAGACTCTTAATCTTGAAACACATAATATAAAAACTAATCCATACT
            CAATTAAAATTTGATTATAATCCCATTTAAATACAAATAATAAAAATAATATTAATACTAATGAAACTAT
            TGACATTAAAATATAGACAAATATATTTATAAAAAATATTAAATTTATTTCCTTTCTAAATAATTTAATA
            GCATCTCTAAAAGGTTGAAAAACCCCTCATAAACCTACTTTATTAGGGCCTTTCCGAATATGAACATAAC
            CTAAAATTTTCCGCTCTAATAATGTAAAAAAAGCCACTCTTACTAAAATACATAAAATTAAAAAAATAAA
            TCTTAAAAAAGAAACCATTATTAAAGGATTTTTATCATAAAGGAAGCTTAAATTCCTTGCATTAAACTTT
            CTGCCACTTTAATTTTCAAACACTAATTGGTAATACCATTTTCAAATTCTAAATTTGATACAATTTTTTC
            TGCCAAATTAGTTTAATATAAAATATAATTTTATAAAAAAAATTTTAATTTTTAATTCCTTTCGTACTAT
            AAAAATAAACTATTTTATATAAGATAGAAACCAACCTGGCTTACGCCGGTCTGAACTCAGATCATGTAGG
            AATTTAAAAGTTGAACAAACTTCTTTCTTTAACTTCTTCACCAAAAAAGAATCCTAATCCAACATCGAGG
            TCGCAAACTATTTTATCTATATGAACTATCCAAAATTATTACGCTGTTATCCCTAGAGTATTTATTTCAT
            TTAATCGCTAAAAACGGAACTTATTTTATAACTAAAAAGATACTTATTCTTTTTTTATCGCCCCAATTAA
            ATTATTAATAATTTAAATTTTAATTATTAACAATAAAAATTCATAGGGTCTTCTTGTCCCTAAATTTTAT
            TTTTGCTTTTGCACTAAAAAAATTAAATTTAATTTTTTAATTAAAGAAAGCTTTTAATTGTTTAATCATT
            CTCTTAGCACTCATTTAAAATCTTATTTCAATACCTTTGTATAGTCAAAATACCACAGCAATTTAAAAAA
            TCATTGAGCAGATTATACATCTTATTACTTTTCAAGATGAAATGTTTTTGATAAACAGTCAATTAAATTA
            ATTTGCCGAATTACTATAATTAAATTTTCATTTTATTAATATATTTTAATTTTTCATTACTTTTTTTTTT
            TAAATTTACTAATTTTTTAATAATTTTATTAAAAATAAATTAATTTAATCATATAAAAATCTTACATAAC
            TTGAATAATAAAAAAATTTTTTACAAAAAAACTTAGAAAATTTTATTCCTTATTTAAATTAATAATTTTT
            ATTTAAAGAAATTCTATTAAGCTTATCCCTAATAGAAAAAATTATATAATTTTTAAAAACTTAAAAAAAT
            AATTTTGATCTAAAATCATAAATTTATAACCAGATATCATTAAATATGAATAAAATTTCATTTCTATTAA
            AATATTGTTTAATATATTTCCACATAATAAAAATATCTTAATAGCTCATTTTAATTTCGGGAAATTAAAA
            TAATTTAATTTATTCTAAAAACCCTAATGCAAAAGGTACCCTAATGAACTTTTATAATTTTACTTTTTAA
            ATTTTTTTCAAAAAATCCTTCACAGTTGAAAAAATAATTTTTCTTTATATAATACAAAAATCTATAATGA
            AATTTTTTAAATTTTCTTATTGAAATTAAATAGTTTTAAAAAATTAAAATGGTTAAACAACAAAATTTTC
            ATTGTAAATGAAACATCGAATGATTTCATTTTAAAAAACACTTTCCAGTATTTTTACTTTGTTACGACTT
            ATCTCACTTCTGAGAGCGACGGGCGATATGTGCATATTTTAGAGCTTGATTCAAATACTCATAATATTAG
            TATTTTACTATTAAATCCTAATTAATTTTTTCATATAAAAAATTACATTAAAATTAATGTAATTCACTTC
            ATTCATAATTATTAGATGCACCTTGACTTAATATATTTTTTTAAAAAAATTTTAAATATAACTATTCAAT
            ATAATTAATATAGTGGTATACAAACTGATTTAAATTACTAAATTAAGTAAGATTAAGGCGTTGTGTCCAT
            CACAGAGCAAATTCCTCTAATAAGCTTAAAATACCGCCAAAATTTTTTAATTTCATAAATTTTATTTACT
            CCTAATATATAGCTTAAAATAATAGGGTATCTAATCCTAGTTTAAAAATTAAATTTTTATAAAATCAAAT
            TAATTTTTTTAAAATTATAAATTTCACCTTTATAAATTTTTAAAATACAAAAATTTTTTTATTATTTTTA
            ATTTTTTAAAAAAAGATTTACTTGTATAACCGCGGCGGCTGGCACAAGTTTAGCCAAATCATTTATCAAA
            CTTCTACTCTATTTTAAAATAGAATTATAAATTTTTCTTCTATTTAAAATATAATTTATTTTATAAAATA
            TAAAGAAAGTTTTATTAATTTTTATTAAAACTACATTTAAATTTATATTTTTTCCTTCTTTTTTTAGACT
            TTAAGAAGGAAAAAATATAGTCTAAATTTAAAAGCATTCCTATGCGTCTTCTTTATGTATGTAATTGTAA
            ATAATTAATATAGATTTCCCTCTCAAGGGAACAATGTTATAGATTTTATCTAAATTTATGTGAAGTAAAC
            TGGTCATCTCTAAAACTTTCGAATATATTTTATGATATGAAACCATGTCTTAAATTAATTTTCTAAGTTA
            ATACAACAACTTATAGATGAAATTTTAAGTGATGCTCCTTATATTTATATAAAATGTTTATTTATTTAAA
            AATTAATAAAAAAACAAAATTTTTTAAAATATAACATTTTTAAAATAAAATGCCTGAGTAAAGGAGTATC
            TTGATAGGATAAATTATGTAATTTTTTTTATTACTTTTATTATATTTTTAGTTTTAATAAAATTAATTTA
            TTTCTTTTAAATTCAAAATTTAACGTGCAAAATTTACACCTAAAACTAATTTT
            """);

    @Test
    public void testShouldZikaGenomeLength() {
        assertEquals(10807, zika.getSequence().length());
    }

    @Test
    public void testShouldIxodesScapularisGenomeLength() {
        assertEquals(14543, ixodesScapularis.getSequence().length());
    }

    @Test
    public void testShouldZikaNucleoBaseComplete() {
        assertEquals(10807, zika.getNbA() + zika.getNbG() + zika.getNbC() + zika.getNbT());

        assertEquals(49.00,
                (double) (zika.getNbA() + zika.getNbT()) / zika.getSequence().length() * 100, 1.00);

        assertEquals(51.00,
                (double) (zika.getNbC() + zika.getNbG()) / zika.getSequence().length() * 100, 1.00);
    }

    @Test
    public void testShouldIxodesScapularisNucleoBaseComplete() {
        assertEquals(14543,
                ixodesScapularis.getNbA() + ixodesScapularis.getNbG()
                        + ixodesScapularis.getNbC() + ixodesScapularis.getNbT());

        assertEquals(78.00,
                (double) (ixodesScapularis.getNbA() + ixodesScapularis.getNbT()) / ixodesScapularis.getSequence().length() * 100,
                1.00);

        assertEquals(22.00,
                (double) (ixodesScapularis.getNbC() + ixodesScapularis.getNbG()) / ixodesScapularis.getSequence().length() * 100,
                1.00);
    }

    @Test
    public void testShouldZikaSearchEnzymes() {
        Map<String, List<Integer>> enzymes = Cutter.searchEnzymes(zika);

        //Positions for Bacillus amyloliquefaciens
        assertEquals(Arrays.asList(4776, 8518), enzymes.get("BamHI"));

        //Position for Serratia marcescens
        assertEquals(List.of(4032), enzymes.get("SmaI"));

        //There no exist position for Klebsiella pneumoniae
        assertEquals(List.of(), enzymes.get("KpnI"));
    }

    @Test
    public void testShouldIxodesScapularisSearchEnzymes() {
        Map<String, List<Integer>> enzymes = Cutter.searchEnzymes(ixodesScapularis);

        //Position for Bacillus amyloliquefaciens
        assertEquals(List.of(4118), enzymes.get("BamHI"));

        //There no exist position for Serratia marcescens
        assertEquals(List.of(), enzymes.get("SmaI"));

        //Position for Klebsiella pneumoniae
        assertEquals(List.of(13129), enzymes.get("KpnI"));
    }
}
